更新 GitHub Actions 工作流程以改善 Cocos Creator 專案建構的成功與失敗處理

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -26,12 +26,19 @@ jobs:
       - uses: actions/checkout@v4
 
       # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: /Applications/CocosCreator/Creator/3.6.2/CocosCreator.app/Contents/MacOS/CocosCreator --project . --build buildConfig/buildConfig_web-mobile.json --force  
-      # run: /Applications/Cocos/Creator/3.6.2/CocosCreator.app/Contents/MacOS/CocosCreator --project . --build buildConfig/buildConfig_web-mobile.json --force
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Build Cocos Creator project
+        id: build_cocos
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          /Applications/CocosCreator/Creator/3.6.2/CocosCreator.app/Contents/MacOS/CocosCreator --project . --build buildConfig/buildConfig_web-mobile.json --force  
+          echo "::set-output name=exit_code::$?"
+        # run: /Applications/Cocos/Creator/3.6.2/CocosCreator.app/Contents/MacOS/CocosCreator --project . --build buildConfig/buildConfig_web-mobile.json --force
+
+      - name: Build Cocos Creator project success
+        if: steps.build_cocos.outputs.exit_code == '36'
+        run: echo "Build succeeded!"
+
+      - name: Build Cocos Creator project failed
+        if: steps.build_cocos.outputs.exit_code != '36'
+        run: |
+          echo "Build failed!"
+          exit 1
