更新 GitHub Actions 工作流程，修正 Cocos Creator 專案建構的退出碼處理，根據退出碼顯示成功或錯誤訊息

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -34,16 +34,11 @@ jobs:
           /Applications/CocosCreator/Creator/3.6.2/CocosCreator.app/Contents/MacOS/CocosCreator --project . --build buildConfig/buildConfig_web-mobile.json --force  
           status=$?
           echo "exitcode=$status"
-          exit 0
-        continue-on-error: true
-        # run: /Applications/Cocos/Creator/3.6.2/CocosCreator.app/Contents/MacOS/CocosCreator --project . --build buildConfig/buildConfig_web-mobile.json --force
-
-      - name: Build Cocos Creator project success
-        if: steps.build_cocos.outputs.exit_code == 36
-        run: echo "Build succeeded!"
-
-      - name: Build Cocos Creator project failed
-        if: steps.build_cocos.outputs.exit_code != 36
-        run: |
-          echo "Build failed! Exit code: ${{ steps.build_cocos.outputs.exit_code }}"
-          exit 1
+          if [ $status == 36 ];
+          then 
+            echo "Build Success"
+            exit 0
+          else 
+            echo "Build Error"
+            exit 1
+          fi
